import type { Metadata } from "next";
import "./globals.css";
import ChildLayout from "./childlayout";

export const metadata: Metadata = {
  title: "Supreme Group",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" style={{ scrollBehavior: 'auto'}}>
      <body className={`antialiased`}>
        <ChildLayout>
          <main className="min-h-[80vh]">
          {children}
          </main>
        </ChildLayout>
      </body>
    </html>
  );
}
